# Generated by Django 5.0 on 2024-01-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user_image',
            new_name='user',
        ),
    ]
