# Generated by Django 5.0 on 2024-01-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_user_image_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='blurhash_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
