# Generated by Django 5.0 on 2024-02-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_artisan'),
        ('workshops', '0007_alter_workshopinfo_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshop'),
        ),
    ]
