# Generated by Django 5.0 on 2024-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_user',
            field=models.TextField(null=True),
        ),
    ]
