# Generated by Django 5.0 on 2024-02-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_base_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='base_user',
        ),
    ]
