# Generated by Django 5.0 on 2024-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_base_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_url',
            field=models.TextField(null=True),
        ),
    ]
