version: '3'

services:

  backend-artizaho-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: dericsolen/artizaho:v1.0
    entrypoint: /apps/entrypoint.sh
    env_file:
      - ./dev.env
    environment:
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=api.settings.dev
    volumes:
      - ".:/apps"
    ports:
      - "9237:8000"
    depends_on:
      - db-artizaho-dev
    stdin_open: true
    tty: true

  db-artizaho-dev:
    image: postgres:16
    container_name: artizaho-database-dev
    env_file:
      - ./dev.env
    restart: always
    volumes:
      - pg_data_artizaho_dev:/var/lib/postgresql/data
    ports:
      - "5732:5432"

volumes:
  pg_data_artizaho_dev:
    external: false
