# Generated by Django 5.0 on 2024-02-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FLORAL', 'FLORAL')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_participants', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('Valid', 'VALID'), ('Rejected', 'REJECTED')], max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_workshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_participant', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'DOLLARS'), ('EUR', 'EURO')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans', to='artisans.artisan')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informations', to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopBookable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available_places', models.IntegerField()),
                ('location', models.TextField()),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in seconds')),
                ('is_available', models.BooleanField(default=False)),
                ('workshop_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookables', to='workshops.workshopinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Paid', 'PAID'), ('Not Paid', 'NOT_PAID')], max_length=125)),
                ('number_of_participants', models.PositiveIntegerField()),
                ('is_custom_workshop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked', to='workshops.customworkshop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('workshop_bookable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked', to='workshops.workshopbookable')),
            ],
        ),
    ]
