# Generated by Django 5.0 on 2024-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customworkshop',
            name='workshop_id',
        ),
        migrations.AlterField(
            model_name='workshopbookable',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
