# Generated by Django 5.0 on 2024-02-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_customworkshop_workshop_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customworkshop',
            name='workshop_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs', to='workshops.workshopinfo'),
        ),
    ]
