# Generated by Django 5.0 on 2024-02-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_remove_workshopreservation_is_custom_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkshop',
            name='status',
            field=models.CharField(choices=[('Valid', 'VALID'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING')], max_length=100),
        ),
        migrations.AlterField(
            model_name='workshopreservation',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('InProgress', 'IN_PROGRESS')], max_length=125),
        ),
    ]
