# Generated by Django 5.0 on 2024-02-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_customworkshop_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopinfo',
            old_name='max_participant',
            new_name='max_participants',
        ),
    ]
