# Generated by Django 5.0 on 2024-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_rename_max_participant_workshopinfo_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'DOLLARS'), ('EUR', 'EURO')], db_default=models.Value('USD'), max_length=5),
        ),
    ]
