# Generated by Django 5.0 on 2024-02-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_alter_workshopinfo_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopbookable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workshopbookable',
            name='time',
        ),
    ]
