# Generated by Django 5.0 on 2024-02-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_workshopbookable_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopbookable',
            name='workshop_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookables', to='workshops.workshopinfo'),
        ),
    ]
