# Generated by Django 5.0 on 2024-02-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_alter_workshopbookable_workshop_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customworkshop',
            name='workshop_info',
        ),
    ]
