# Generated by Django 5.0 on 2024-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_customworkshop_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customworkshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customworkshop',
            name='is_enterprise',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customworkshop',
            name='status',
            field=models.CharField(choices=[('Valid', 'VALID'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING'), ('New', 'NEW')], default='New', max_length=100),
        ),
    ]
