# Generated by Django 5.0 on 2024-02-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_customworkshop_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopinfo',
            name='artisan',
        ),
    ]
