# Generated by Django 5.0 on 2024-02-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_rename_availabity_artisantimeavailability_availability'),
        ('workshops', '0014_remove_workshopinfo_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopbookable',
            name='artisan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookable_workshops', to='artisans.artisan'),
        ),
    ]
