# Generated by Django 5.0 on 2024-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_workshopbookable_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopbookable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
