# Generated by Django 5.0 on 2024-03-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_workshopbookable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopreservation',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('InProgress', 'IN_PROGRESS'), ('Not Paid', 'NOT_PAID')], max_length=125),
        ),
    ]
