# Generated by Django 5.0 on 2024-03-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_rename_availabity_artisantimeavailability_availability'),
        ('workshops', '0017_alter_workshopreservation_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopreservation',
            name='artisan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_workshop', to='artisans.artisan'),
        ),
    ]
