# Generated by Django 5.0 on 2024-03-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0019_alter_workshopreservation_custom_workshop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopinfo',
            name='base_price',
        ),
        migrations.AddField(
            model_name='workshopbookable',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
