# Generated by Django 5.0 on 2024-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender_alter_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='account_type',
        ),
        migrations.AddField(
            model_name='user',
            name='nif',
            field=models.TextField(null=True),
        ),
    ]
