# Generated by Django 5.0 on 2024-02-18 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('artisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='artisans.artisan')),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanTimeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availabity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='artisans.artisanavailability')),
            ],
        ),
    ]
