# Generated by Django 5.0 on 2024-02-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_artisanavailability_artisantimeavailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisantimeavailability',
            old_name='availabity',
            new_name='availability',
        ),
    ]
