name: Push docker image to Hub

on:
    pull_request:
        branches:
            - main

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
          name: Check out code

        - name: Build and Push Docker Image
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: artizaho/artizaho-dev
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          